# Generated by Django 6.1 on 2026-10-09 08:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('yard', 'Yard'), ('raised_bed', 'Raised Bed'), ('indoor_pot', 'Indoor Pot'), ('greenhouse', 'Greenhouse'), ('other', 'Other')], default='raised_bed', max_length=20)),
                ('rows', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('cols', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vegetable name, e.g. Lettuce', max_length=120)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('planting_date', models.DateField(default=datetime.date.today)),
                ('days_to_harvest', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('seed', 'Seed'), ('seedling', 'Seedling'), ('growing', 'Growing'), ('flowering', 'Flowering'), ('ready', 'Ready to harvest'), ('harvested', 'Harvested'), ('dead', 'Dead')], default='seedling', max_length=20)),
                ('water_every_days', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('fertilize_every_days', models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('pos_x', models.PositiveIntegerField(default=0)),
                ('pos_y', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='farm.gardenarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('watered', models.BooleanField(default=False)),
                ('fertilized', models.BooleanField(default=False)),
                ('health', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='good', max_length=20)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to='farm.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('growth', 'Growth progress'), ('pest', 'Pest issue'), ('weather', 'Weather change'), ('note', 'Note')], default='note', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='farm.plant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('water', 'Water'), ('fertilize', 'Fertilize'), ('harvest', 'Harvest'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='farm.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gardenarea',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_area_per_user'),
        ),
        migrations.AddConstraint(
            model_name='dailycheck',
            constraint=models.UniqueConstraint(fields=('plant', 'date'), name='unique_check_per_plant_day'),
        ),
    ]
