# Generated by Django 6.1 on 2026-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='postponed_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='weather_paused',
            field=models.BooleanField(default=False),
        ),
    ]
