# Generated by Django 6.1 on 2026-10-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_reminder_postponed_from_reminder_weather_paused'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardenarea',
            options={'ordering': ['name'], 'verbose_name': 'Modular Garden Plot', 'verbose_name_plural': 'Modular Garden Plots'},
        ),
    ]
