# Generated by Django 6.1 on 2026-10-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_gardenarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardenarea',
            options={'ordering': ['name']},
        ),
    ]
