# Generated by Django 6.1 on 2026-10-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_gardenarea_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='care_photos/%Y/%m/'),
        ),
    ]
